version: "3"

services:
  pet_home:
    image: pet_home
    environment:
      - DB_URI=/app/pet_home.mv.db
#    ports:
#      - "8080:8080"
    container_name: pet_home
    networks:
      pet_home_net:
        ipv4_address: 172.50.0.10
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5
  pet_home_testing:
    environment:
      - ADDR=172.50.0.10
    image: pet_home_testing
    depends_on:
      - pet_home
    container_name: pet_home_testing
    networks:
      pet_home_net:
        ipv4_address: 172.50.0.101
networks:
  pet_home_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16